name: Deploy Workflow
 
on:
  workflow_call:
    inputs:
      deployVersion:
        required: false
        type: string
      deployTarget:
        required: false
        type: string
 
jobs:
  deploy:
    name: Deploy APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Simulate Deployment
        run: |
          echo "Version: ${{ inputs.deployVersion }}"
          echo "Target: ${{ inputs.deployTarget }}"
          exit 1
          
      - name: Notify about failed deploy
        if: failure()
        shell: pwsh
        run: |          
          $repoId = "${{ github.repository }}"
          $runId = "${{ github.run_id }}"          
          $message = "[See deployment](https://github.com/$repoId/actions/runs/$runId)"
          echo "Message: $message"  
